### ISSUE TITLE
[Question] Remembering the last opened tab

### ISSUE THREAD

**Issue by dhduc** [CodyHouse/cd-tabs-changelog#1]
Hi there,
When I reload a page contain the tabs component, how can I open the last opened tab?
Thanks.

**Comment by claudia-romano** [comment]
Hi there,
this option is not still available at the moment, but we'll make sure to updated the component as soon as possible to include deep linking as well.

Cheers!

**Comment by claudia-romano** [comment]
Hi,
we've updated the tabs component to include the deep link option, that you can use to preserve the last opened tab selection.
You can read more about that here:
https://codyhouse.co/ds/components/info/tabs#deep-linking

And get the updated code here:
https://codyhouse.co/ds/components/app/tabs

Cheers!
