### ISSUE TITLE
Tabs not working in Chrome

### ISSUE THREAD

**Issue by richardwiggins** [CodyHouse/cd-tabs-changelog#4]
I've started getting JS issues with the tabs in Chrome, though I'm sure this was working at some point.

I'm using 3.0.14.

When clicking on any tabs I'm getting the following errors:

`scripts.min.js:1 Uncaught TypeError: Util.toggleClass is not a function
    at t.triggerTab (scripts.min.js:1:31265)
    at HTMLUListElement.<anonymous> (scripts.min.js:1:30143)
t.triggerTab @ scripts.min.js:1
(anonymous) @ scripts.min.js:1`

This is referring to these lines:
`Util.toggleClass(this.panels[n], this.hideClass, !s),`

and;
`t.target.closest(".js-tabs__trigger") && n.triggerTab(t.target.closest(".js-tabs__trigger"), t)`

**Comment by claudia-romano** [comment]
Hi there, what version of the component are you using (e.g., CodyFrame v4, CodyFrame v3)? Thanks

**Comment by claudia-romano** [comment]
Hi there, the JS of the component comes with some utility functions, for example, the toggleClass function. Could you double check that you have included those too?
You can find them when copying the code:
https://codyhouse.co/ds/components/app/tabs

Thanks!

**Comment by richardwiggins** [comment]
Just checked and the code is correct but worked out that it's something in the minification I think. I swapped to the non-minified version and that seems to be okay.

Any ideas?

Here's the packages I'm using:

`"devDependencies": {
    "autoprefixer": "^9.4.3",
    "browser-sync": "^2.26.3",
    "codyhouse-framework": "^3.0.14",
    "gulp": "^4.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-postcss": "^8.0.0",
    "gulp-purgecss": "^3.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-sass": "^5.0.0",
    "gulp-sass-glob": "git+https://github.com/CodyHouse/gulp-sass-glob.git",
    "gulp-uglify": "^3.0.2",
    "postcss-calc": "^7.0.1",
    "postcss-css-variables": "git+https://github.com/CodyHouse/postcss-css-variables.git",
    "sass-embedded": "^1.0.0-beta.4"
  },`

**Comment by claudia-romano** [comment]
Hi there, I use the same packages but I don't seem to have the same issue. Did you try minifying only the component  code? This is to make sure the issue is with the component JS and not with some other JS that is imported before the component. Thanks.
